import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Lora } from "next/font/google";

import "./globals.css";
import MinimalNav from "./_components/MinimalNav";
import Footer from "./_components/Footer";
import BackToTop from "./_components/BackToTop";

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-lora',
  display: 'swap',
});

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Liliana E Correa",
  // description: "Generated by create next app",,
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth" style={{ backgroundColor: '#323334' }}>
      <body className={`${lora.variable} ${inter.variable} font-serif`}>
        <MinimalNav />
        <main className="w-full mx-auto relative">
          {children}
        </main>
        {modal}
        <BackToTop />
        <Footer />
      </body>
    </html >
  );
}
