import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Playfair_Display } from '@next/font/google';

import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify weights as needed
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Liliana E Correa",
  // description: "Generated by create next app",,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gradient-to-r from-[#323334] to-[#313130] ${playfairDisplay.className}`}>
        <Header />
        <main className="w-full mx-auto tabletAndBelow:px-4 max-w-[1280px] pl-[4rem]">
          {children}
        </main>
        <Footer />
      </body>
    </html >
  );
}
